### ISSUE TITLE
bitwarden@2023.3.0: download via aria2 failed

### ISSUE THREAD

**Issue by javerVip** [anderlli0053/DEV-tools#124]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by anderlli0053** [comment]
@javerVip  


Cannot reproduce.

All files could be downloaded without any issue.
Problems with download could be caused by:

Network error
Blocked site (Great Firewall of China, Corporate restrictions, ...)
Antivirus settings blocking URL/downloaded file
Proxy configuration
Aria2 being unreliable (if you're facing problems with aria2, disable it by running scoop config aria2-enabled false and try again)
