### ISSUE TITLE
msvc manifests auto update conflicts

### ISSUE THREAD

**Issue by tree-s** [anderlli0053/DEV-tools#2]
## Bug Report

**Package Name:** [msvc@2019]

### Current Behaviour

Fails to install with the command `scoop install msvc@2019`

### Expected Behaviour

The manifest runs and the install completes.

### Additional context/output

This is probably also a problem with other manifests. Maybe I'm also not installing properly?

### Possible Solution

Update the manifests file. Perhaps rename to avoid the auto update syntax with the latest scoop version.

### System details

**Windows version:** [11]

**OS architecture:** [64bit]

**PowerShell version:** [major[5] minor[1] Build[22000] Rev[653]]

**Additional software:** [N/A]

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-07-27T16:20:53.2131282-02:30",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by anderlli0053** [comment]
Hello!

Thanks for reporting the bug!

I tried to fix it, but the  MSVC scripts  were wroten by Rivy ( https://github.com/rivy/scoop-bucket ). I have disabled / deprecated them as they don't work in the original repository neither and i was unable to find the right solution. They rely on external batch file, which also appears to be broken and beside all of that, the download links for all available MSVCs are faulty / erroneus and return 404 when i lastly tested them.  They use SCP (Secure Copy protocol), which is also not desirable or even non operable in Scoop as we all can see.  Since he wrote the manifest for MSVCs it would be a good idea for him to fix that however he knows it is the best to fit. I will eventually update this bucket with his upstream!

**Comment by tree-s** [comment]
Thanks for the update I have written a scoop manifest for msvc2019 before, but it was not auto updatable and didn't really follow the scoop mindset/protocol. I was hoping that there was a nice solution and this looked like it for the build tools.

I'll check out Rivy's bucket and try there and add an issue.

--michael

**Comment by anderlli0053** [comment]
No problem, as I have said; This buckets also upstreams from other buckets, so that means if specific manifest is corrupted in the original bucket, than the corrupted JSON will also be present in this bucket and what's even more, marked as OK and installable by Github Actions BOT.

Regards,

Andrew
