### ISSUE TITLE
[Request] please add iFind (a financial data tool)

### ISSUE THREAD

**Issue by NoPKU** [anderlli0053/DEV-tools#46]
### iFind 

**iFind.exe

**Description: a financial data tool

**Homepage:  [https://www.51ifind.com]

**Download link(s):** [https://resource.thsi.cn/download/iFinD/iFinD_Setup_v1.10.12.384.001.exe]

**Comment by anderlli0053** [comment]
@NoPKU Is the `iFinD.exe` executable the correct one to start with? Because there are many others in Chinese or something that i cannot graspmy head around, even with the help of Google Translate..  The executables are named like this -->  `点击启动同花顺iFinD`  The hell does that even mean? The translator translates it roughly in `Click to start straight flush iFinD` .. like what the hell? what straight flush? this ain't poker 🤣

**Comment by anderlli0053** [comment]
@NoPKU  Done, run `scoop update && scoop install ifind`
