### ISSUE TITLE
choice   rongda-zhihuiyun  wind-financial-tool   updates 

### ISSUE THREAD

**Issue by NoPKU** [anderlli0053/DEV-tools#58]
Current version in bucket：
choice              V1.2.17.0         ander  2022-11-04 13:35:34
rongda-zhihuiyun    V2.8.6            ander  2022-10-28 19:10:47
wind-financial-tool   V22.8.0           ander  2022-10-28 20:24:35

Newest version：
choice   V6.3.1.1      https://choiceupdates.eastmoney.com/Choice/OfflinePackage/6.3.1.1/ChoiceSetupLocal.exe
rongda-zhihuiyun    V3.0.5     https://download.rongdasoft.com/update/prod/300/Rd_IBSaas_V3.0.5.exe
wind-financial-tool   V22.8.1   https://d-cdn.wind.com.cn/windnet/WFT_Setup_CHS.zip

**Comment by anderlli0053** [comment]
Fixed, although i had to remove the `hash` properties to refrain from hash checking as my internet connection is slow at the time being, so each one of these programs is about 300-500MB, and since they are hosted in Asia my speed is like 2kB/s. Of course that means that i am unable to download the software from the servers in required time span to calculate hashes and then to just delete the installers... It should still work
